# ======================================================================================
# Fichier : dbt/dbt_project.yml
# Objet   : Configuration du projet dbt pour Sport Data Solution (stack Postgres)
# ======================================================================================

name: sportdata
version: "1.0"
config-version: 2

# Doit correspondre à la clé racine de profiles.yml (voir ci-dessous)
profile: sportdata

# Répertoires du projet (DBT >= 1.x) — valeurs par défaut explicites
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

# Dossiers de sortie & nettoyage
target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Matérialisation par défaut et conventions par sous-dossier
models:
  sportdata:
    +materialized: view   # défaut "safe" pour le dev
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
