# ======================================================================================
# Fichier : dbt/profiles.yml
# Objectif : Configuration de la connexion PostgreSQL pour dbt
# ======================================================================================
# Configuration DBT pour le projet sportdata

sportdata:
  target: dev        # Environnement actif (dev/test/prod)
  outputs:
    dev:
      type: postgres              # Type de base de données
      host: sport-postgres        # Nom du conteneur PostgreSQL
      user: user                  # Identifiant (cf. .env)
      password: password          # Mot de passe (cf. .env)
      port: 5432                  # Port PostgreSQL exposé en interne
      dbname: sportdata           # Nom de la base de données
      schema: public              # Schéma de destination des modèles
      threads: 1                  # Nombre de connexions en parallèle
      keepalives_idle: 0         # (optionnel)
      connect_timeout: 10        # (optionnel)
