# ==========================================================================================
# Fichier    : docker-compose.override.airflow.yml (full .env)
# Objectif   : Ajouter Airflow (orchestration, ETL, workflows) à la stack Sport Data Solution
# Auteur     : Xavier Rousseau | Juin 2025
#
# --- Mode d'emploi ---
# Ce fichier complète (override) le docker-compose principal.
# Il permet :
#   - Un déploiement Airflow désactivable (ajoute/retire juste cet override)
#   - Une configuration 100% pilotée par .env (aucune info sensible ici)
#   - Montage direct des dossiers projets, logs, plugins, dbt et great_expectations
#   - Séquence de démarrage orchestrée (init → webserver → scheduler → worker → flower)
#   - Prêt pour la prod, la CI, l’audit, la transmission
# ==========================================================================================
services:

  # ========================================================================================
  # 1. sport-airflow-init
  #   🛠 Service d’initialisation Airflow :
  #      - Installe les dépendances Python (requirements.txt)
  #      - Initialise la base (airflow db init)
  #      - Crée le compte admin (admin user dans l’UI)
  #   🔁 Ne tourne qu’une fois au démarrage (restart: "no")
  #   ⚠️ Doit être relancé après un reset complet de la DB
  # ========================================================================================
  sport-airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow     # Image custom basée sur Airflow officiel
    image: sport-airflow:latest          # Nom de l’image personnalisée
    container_name: sport-airflow-init
    depends_on:
      - sport-postgres                   # Attend la base de données
      - sport-redis                      # Attend le broker Celery
    restart: "no"
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/dbt:/opt/airflow/dbt
      - ./airflow/great_expectations:/opt/airflow/great_expectations
      - ./requirements.txt:/requirements.txt
    entrypoint:
      - bash
      - -c
      - |
        pip install -r /requirements.txt && \
        airflow db init && \
        airflow users create \
          --username ${AIRFLOW_ADMIN_USER} \
          --firstname ${AIRFLOW_ADMIN_FIRSTNAME} \
          --lastname ${AIRFLOW_ADMIN_LASTNAME} \
          --role Admin \
          --email ${AIRFLOW_ADMIN_EMAIL} \
          --password ${AIRFLOW_ADMIN_PASSWORD}
    networks:
      - sportdata_net

  # ========================================================================================
  # 2. sport-airflow-webserver
  #   🌐 UI web principale (http://localhost:${AIRFLOW_WEB_PORT})
  #      - Visualise, lance, monitore les DAGs
  #      - Peut être redémarré à chaud (restart: unless-stopped)
  #   ⚠️  Dépend de l’init pour être sûr que la DB/users Airflow existent déjà
  # ========================================================================================
  sport-airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: sport-airflow:latest
    container_name: sport-airflow-webserver
    restart: unless-stopped
    depends_on:
      - sport-airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    ports:
      - "${AIRFLOW_WEB_PORT}:8080"           # Port externe pour accès navigateur
    command: airflow webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/dbt:/opt/airflow/dbt
      - ./airflow/great_expectations:/opt/airflow/great_expectations
      - ./requirements.txt:/requirements.txt
    networks:
      - sportdata_net

  # ========================================================================================
  # 3. sport-airflow-scheduler
  #   ⏰ Service planificateur :
  #      - Détecte quand déclencher/exécuter les DAGs (selon leur schedule/trigger)
  #   ⚠️  Démarre après le webserver (séquencement optimal)
  #   ⚡️  Peut être scalé si très grosse volumétrie (rarement utile hors prod XXL)
  # ========================================================================================
  sport-airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: sport-airflow:latest
    container_name: sport-airflow-scheduler
    restart: unless-stopped
    depends_on:
      - sport-airflow-webserver
      - sport-redis
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    command: airflow scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/dbt:/opt/airflow/dbt
      - ./airflow/great_expectations:/opt/airflow/great_expectations
      - ./requirements.txt:/requirements.txt
    networks:
      - sportdata_net

  # ========================================================================================
  # 4. sport-airflow-worker
  #   ⚙️  Worker Celery pour exécution distribuée des tasks
  #      - Peut être multiplié si besoin (scaling horizontal)
  #      - Peut être monitoré par Flower
  #   ⚠️  Démarre après le scheduler pour bonne synchronisation
  # ========================================================================================
  sport-airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: sport-airflow:latest
    container_name: sport-airflow-worker
    restart: unless-stopped
    depends_on:
      - sport-airflow-scheduler
      - sport-redis
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    command: airflow celery worker
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/dbt:/opt/airflow/dbt
      - ./airflow/great_expectations:/opt/airflow/great_expectations
      - ./requirements.txt:/requirements.txt
    networks:
      - sportdata_net

  # ========================================================================================
  # 5. sport-flower
  #   📈 Monitoring des workers Celery via Flower (http://localhost:${AIRFLOW_FLOWER_PORT})
  #      - Visualise l’état des workers, tasks, files d’attente, stats d’exécution
  #      - Indispensable pour debug, monitoring ou scaling
  #      - Peut être désactivé si usage ultra-minimaliste
  #   ⚠️  Démarre après les workers pour collecter les stats
  # ========================================================================================
  sport-flower:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: sport-airflow:latest
    container_name: sport-flower
    restart: unless-stopped
    depends_on:
      - sport-airflow-worker
      - sport-redis
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    command: airflow celery flower
    ports:
      - "${AIRFLOW_FLOWER_PORT}:5555"
    volumes:
      - ./requirements.txt:/requirements.txt
    networks:
      - sportdata_net


# ==========================================================================================
# FIN DE FICHIER — docker-compose.override.airflow.yml
# ==========================================================================================
