# ==========================================================================================
# Fichier    : docker-compose.override.metabase.yml (full .env)
# Objectif   : Ajouter Metabase pour exploration BI/visualisation des données PostgreSQL
# Auteur     : Xavier Rousseau | Juin 2025
#
# Ce fichier permet d’ajouter à la stack :
#   - Un outil BI no-code (Metabase) pour explorer les données, créer dashboards, KPIs, exports.
#   - Configuration 100% par .env (aucune info sensible ou statique dans ce fichier).
#   - Prêt pour usage local, cloud, CI/CD, démo client, onboarding équipe.
# ==========================================================================================


services:

  # ----------------------------------------------------------------------------------------
  # sport-metabase — Service d’exploration BI/visualisation des données PostgreSQL
  #
  # 🎯  Rôle : Permet d’explorer, requêter, visualiser, partager et exporter les données métiers,
  #            sans écrire de code SQL.
  #
  # 🔗  Accès web : http://localhost:${METABASE_PORT} (port externe configurable via .env)
  #
  # 🗄  Persistance de la configuration Metabase (utilisateurs, connexions, dashboards…) :
  #     - Si besoin, monter un volume local (voir docs Metabase), non requis pour un simple POC.
  #
  # ⚡️  Démarrage :
  #     - Attends que PostgreSQL soit prêt (`depends_on`)
  #     - Se connecte directement à la base métier grâce aux variables d’environnement propagées.
  # ----------------------------------------------------------------------------------------
  sport-metabase:
    image: metabase/metabase                      # Image officielle Metabase (auto-upgradable)
    container_name: sport-metabase
    restart: always

    # -----------------------------------------------------------
    # Expose le port web Metabase à l’hôte (par défaut : 3000)
    # Variable ${METABASE_PORT} pilotée via .env (évite conflits)
    # -----------------------------------------------------------
    ports:
      - "${METABASE_PORT}:3000"

    # -----------------------------------------------------------
    # Ne démarre qu’après PostgreSQL (critique pour la connexion)
    # -----------------------------------------------------------
    depends_on:
      - sport-postgres

    # -----------------------------------------------------------
    # Paramètres d’environnement :
    # - Connexion automatique à la base métier
    # - Personnalisation du fuseau horaire JVM si besoin
    # -----------------------------------------------------------
    environment:
      MB_DB_TYPE: postgres                # Utilise PostgreSQL comme backend
      MB_DB_DBNAME: ${POSTGRES_DB}        # Nom de la base de données cible
      MB_DB_PORT: ${POSTGRES_PORT}        # Port d’écoute de PostgreSQL
      MB_DB_USER: ${POSTGRES_USER}        # Utilisateur DB (sécurisé via .env)
      MB_DB_PASS: ${POSTGRES_PASSWORD}    # Mot de passe DB (sécurisé via .env)
      MB_DB_HOST: ${POSTGRES_HOST}        # Hôte du service DB (service compose)
      JAVA_TIMEZONE: ${MB_TIMEZONE}       # Fuseau horaire JVM (optionnel, via .env)
    networks:
      - sportdata_net

# ==========================================================================================
# FIN DE FICHIER — docker-compose.override.metabase.yml
# ==========================================================================================
