# ====================================================================================
# FICHIER : docker/docker-compose.override.airflow.yml
# OBJET   : Déploiement modulaire d’Apache Airflow avec CeleryExecutor
# CONTEXTE : Stack distribuée — Redis (broker), PostgreSQL (backend), DAGs locaux
# ====================================================================================

# --------------------------------------------------------------------------
# 🔁 Bloc commun à tous les services Airflow (réutilisé avec <<)
# --------------------------------------------------------------------------
x-airflow-common: &airflow-common
  build: ./airflow  # 📦 Image construite localement depuis le Dockerfile dans ./airflow

  environment:
    # 🧠 Mode d’exécution d’Airflow
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor

    # 🗄 Connexion au backend PostgreSQL
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    # 💬 Configuration de Celery (broker Redis + backend PostgreSQL)
    AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    # 🔐 Sécurité
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}

    # ⚙️ Options de démarrage
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    # 🔔 Notifications NTFY (injectées dans tous les services Airflow)
    NTFY_URL: http://sport-ntfy:80
    NTFY_TOPIC: sportdata_activites

  volumes:
    # 📂 Dossiers locaux montés dans les conteneurs
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/scripts:/opt/airflow/scripts
    - ./airflow/data:/opt/airflow/data
    - ./airflow/tests:/opt/airflow/tests
    - ./.env:/opt/airflow/.env:ro

  networks:
    - sport-network

  depends_on:
    sport-postgres:
      condition: service_healthy
    sport-redis:
      condition: service_healthy

# --------------------------------------------------------------------------
# 1️⃣ Webserver — Interface Web Airflow (http://localhost:8092)
# --------------------------------------------------------------------------
services:
  sport-airflow-webserver:
    <<: *airflow-common
    container_name: sport-airflow-webserver
    command: webserver
    ports:
      - "8092:8080"

# --------------------------------------------------------------------------
# 2️⃣ Scheduler — Planification des DAGs
# --------------------------------------------------------------------------
  sport-airflow-scheduler:
    <<: *airflow-common
    container_name: sport-airflow-scheduler
    command: scheduler

# --------------------------------------------------------------------------
# 3️⃣ Worker — Exécution des tâches via Celery
# --------------------------------------------------------------------------
  sport-airflow-worker:
    <<: *airflow-common
    container_name: sport-airflow-worker
    command: celery worker

# --------------------------------------------------------------------------
# 4️⃣ Flower — UI de monitoring des workers (http://localhost:5566)
# --------------------------------------------------------------------------
  sport-flower:
    image: sport-airflow  # ✅ On utilise l'image personnalisée qui contient Flower
    container_name: sport-flower
    entrypoint: ["celery", "--app", "airflow.executors.celery_executor.app", "flower"]
    ports:
      - "5566:5555"
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      sport-redis:
        condition: service_healthy
      sport-airflow-worker:
        condition: service_started
    networks:
      - sport-network
