# ====================================================================================
# FICHIER   : docker/docker-compose.override.pgadmin.yml
# OBJET     : Déploiement de pgAdmin (UI web d'administration PostgreSQL)
# CONTEXTE  : Interface simple pour gérer PostgreSQL manuellement depuis le navigateur
# ====================================================================================

services:

  # ------------------------------------------------------------------------------
  # 🛠️ Service pgAdmin — Interface d’administration de la base PostgreSQL
  # ------------------------------------------------------------------------------
  sport-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sport-pgadmin

    ports:
      - "${PGADMIN_PORT}:80"  # UI accessible via http://localhost:5050

    environment:
      # 👤 Compte administrateur pgAdmin
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

      # ⚙️ Port d’écoute interne (toujours 80 dans l’image officielle)
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}

    volumes:
      # 💾 Volume persistant : stocke les connexions, favoris, config utilisateur
      - pgadmin_data:/var/lib/pgadmin

    restart: unless-stopped  # 🔁 Redémarre automatiquement sauf arrêt manuel

    depends_on:
      sport-postgres:
        condition: service_healthy  # ✅ Attend que PostgreSQL soit prêt

    healthcheck:
      # ❤️ Vérifie que l’interface web de pgAdmin est disponible
      test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - sport-network  # 🌐 Réseau partagé avec les autres services

# ------------------------------------------------------------------------------
# 🌐 Réseau Docker commun à toute la stack
# ------------------------------------------------------------------------------
networks:
  sport-network:
    driver: bridge

# ------------------------------------------------------------------------------
# 💾 Volume persistant pour les données utilisateur pgAdmin
# ------------------------------------------------------------------------------
volumes:
  pgadmin_data:
