# ====================================================================================
# FICHIER : docker-compose.override.metabase.yml
# OBJET  : Déploiement de Metabase (interface BI no-code connectée à PostgreSQL)
# ====================================================================================

services:

  # ============================================================================
  # 1. Metabase — BI visuelle no-code pour créer des dashboards métiers
  # ============================================================================
  sport-metabase:
    image: metabase/metabase:latest
    container_name: sport-metabase
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: ${POSTGRES_HOST}
      MB_TIMEZONE: ${MB_TIMEZONE}
    volumes:
      - metabase_data:/metabase
    restart: unless-stopped
    depends_on:
      sport-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sport-network

# ====================================================================================
# Réseau partagé avec les autres services
# ====================================================================================
networks:
  sport-network:
    driver: bridge

# ====================================================================================
# Volume persistant pour conserver les tableaux de bord et la config Metabase
# ====================================================================================
volumes:
  metabase_data:
