# ====================================================================================
# FICHIER : docker-compose.override.dbt.yml
# OBJET  : Déploiement de DBT (modélisation et transformation SQL)
# ====================================================================================

services:

  sport-dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.13
    container_name: sport-dbt
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app                         # Projet DBT complet (doit contenir dbt_project.yml)
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml  # Fichier de configuration DBT (standard)
    environment:
      DBT_PROFILES_DIR: /root/.dbt
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      DBT_TARGET: ${DBT_TARGET}
    command: tail -f /dev/null                 # Garde le container actif pour exécution manuelle
    healthcheck:
      test: ["CMD-SHELL", "dbt --version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      sport-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sport-network

# ====================================================================================
# Réseau partagé avec le reste de la stack
# ====================================================================================
networks:
  sport-network:
    driver: bridge
