# ====================================================================================
# FICHIER : docker-compose.override.pgadmin.yml
# OBJET  : Déploiement de pgAdmin (UI web d'administration PostgreSQL)
# ====================================================================================

services:

  # ============================================================================
  # 1. pgAdmin — Interface web complète pour gérer PostgreSQL
  # ============================================================================
  sport-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sport-pgadmin
    ports:
      - "${PGADMIN_PORT}:80"   # Port externe (UI accessible via http://localhost:5050)
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}  # Généralement 80 en interne
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      sport-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - sport-network

# ====================================================================================
# Réseau partagé
# ====================================================================================
networks:
  sport-network:
    driver: bridge

# ====================================================================================
# Volume pour stocker les connexions, favoris, utilisateurs
# ====================================================================================
volumes:
  pgadmin_data:
